import type { ColorTheme,TaskEvent } from "../../shared/contracts";
import { createInteractionView } from "../interaction-view";
import { type ModelMenu } from "../model-menu";
import {
type TokenPrices,type UsageSummary
} from "../presentation";
import { createRepositoryView } from "../repository-view";
import {
type PreviousTurnOptions
} from "../session-view";
import { type FileDiff,type StreamView } from "../stream-view";
import { type TaskHistoryEntry } from "../task-history";
import type { WorkspaceChooserControl } from "../workspace-chooser";
import type { ImageAttachment } from "../../shared/image-input";
import type { ComposerImages } from "../attachments/composer-images";

export type RunState = "send" | "running" | "stopped" | "paused" | "waiting" | "stopping";
export interface ComposerMessage { text: string; images: ImageAttachment[]; }

/** 当前桌面视图的状态与各功能控制器；由 main.ts 组装。 */
export interface RendererApp {
  terminalStatuses: Set<string>;
  statusLabels: Record<string, string>;
  workspaceKey: "bit-agent.workspace-root.v1";
  inspectorKey: "bit-agent.inspector-collapsed.v1";
  reportClientError: (kind: "exception" | "rejection", line?: number | undefined) => void;
  initialTheme: ColorTheme;
  shell: HTMLElement;
  gatewayUrl: string;
  workspaceInput: HTMLInputElement;
  workspaceName: HTMLElement;
  workspaceSummary: HTMLElement;
  objectiveInput: HTMLTextAreaElement;
  objectiveDisplay: HTMLElement;
  runButton: HTMLButtonElement;
  retryButton: HTMLButtonElement;
  newTaskButton: HTMLButtonElement;
  cancelButton: HTMLButtonElement;
  browseButton: HTMLButtonElement;
  statusText: HTMLElement;
  taskIdText: HTMLElement;
  currentTurn: HTMLElement;
  files: HTMLElement;
  tests: HTMLElement;
  lint: HTMLElement;
  acceptance: HTMLElement;
  verificationNotes: HTMLUListElement;
  rounds: HTMLElement;
  usageState: HTMLElement;
  usageCard: HTMLElement;
  connectionDot: HTMLElement;
  taskHistory: HTMLElement;
  historyCount: HTMLElement;
  historyEmpty: HTMLElement;
  emptyState: HTMLElement;
  errorActions: HTMLElement;
  inspectorToggle: HTMLButtonElement;
  inspectorClose: HTMLButtonElement;
  inspectorResize: HTMLElement;
  themeToggle: HTMLButtonElement;
  tasksNavigation: HTMLButtonElement;
  repositoryNavigation: HTMLButtonElement;
  taskSidebarPane: HTMLElement;
  repositorySidebarPane: HTMLElement;
  repositoryView: HTMLElement;
  repository: ReturnType<typeof createRepositoryView>;
  activeTaskId: string | null;
  stoppedTaskId: string | null;
  stoppedTasks: Set<string>;
  stopTask: () => Promise<void>;
  activeSessionId: string | null;
  activeWorkspaceRoot: string;
  submitting: boolean;
  viewGeneration: number;
  nextSessionOffset: number | null;
  activeObjective: string;
  activeImages: ImageAttachment[];
  composerImages: ComposerImages | null;
  replaying: boolean;
  history: TaskHistoryEntry[];
  conversationScroller: HTMLElement;
  streamView: StreamView;
  processCache: Map<string, Node[]>;
  processLoaders: Map<string, { view: StreamView; answer: string; done(): void; fail(error: Error): void }>;
  searchResults: TaskHistoryEntry[] | null;
  sessionSearch: HTMLInputElement;
  activeView: "tasks" | "repository";
  interactionView: ReturnType<typeof createInteractionView> | null;
  modelMenu: ModelMenu | null;
  workspaceChooser: WorkspaceChooserControl | null;
  interactionRefreshSequence: number;
  renameIcon: "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 20h4L19 9l-4-4L4 16zM13.5 6.5l4 4\"/></svg>";
  deleteIcon: "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 7h14M10 7V5h4v2M7 7l1 12h8l1-12\"/></svg>";
  searchTimer: ReturnType<typeof setTimeout> | undefined;
  searchSequence: number;
  defaultPlaceholder: string;
  supplementStatuses: Set<string>;
  RUN_ICONS: { send: string; running: string; paused: string; stopped: string; };
  RUN_LABELS: Record<RunState, string>;
  steerChoice: HTMLElement;
  composerContext: HTMLElement;
  queued: ComposerMessage[];
  queuedList: HTMLOListElement;
  permissionOrder: readonly ["confirm", "edit", "read_only"];
  resizingInspector: boolean;
  diffLoader: (taskId: () => string | null) => (callId: string) => Promise<FileDiff[]>;
  keepProcess: (taskId: string, nodes: Node[]) => void;
  dropProcesses: () => void;
  previousTurnOptions: () => PreviousTurnOptions;
  routeProcessEvent: (event: TaskEvent) => boolean;
  setTheme: (theme: ColorTheme, syncWindow?: boolean) => void;
  setWorkspace: (path: string) => void;
  setActiveView: (view: "tasks" | "repository") => void;
  renderHistory: () => void;
  newConversationIn: (root: string) => void;
  historyRow: (entry: TaskHistoryEntry) => HTMLElement;
  startRename: (entry: TaskHistoryEntry, title: HTMLElement) => void;
  deleteConversation: (entry: TaskHistoryEntry) => Promise<void>;
  searchSessions: (query: string) => Promise<void>;
  upsertHistory: (entry: TaskHistoryEntry) => void;
  updateActiveHistory: (update: Partial<TaskHistoryEntry>) => void;
  requestInput: () => { gatewayUrl: string; taskId: string; };
  setBusy: (busy: boolean) => void;
  composerMode: () => "new" | "supplement" | "answer" | "locked";
  fitComposer: () => void;
  runState: () => RunState;
  paintRunButton: () => void;
  primaryAction: () => Promise<void>;
  paintComposer: () => void;
  renderQueue: () => void;
  enqueue: () => void;
  sendQueued: (status: string) => void;
  clearQueue: () => void;
  setStatus: (status: string) => void;
  applyInteractionTask: (task: Record<string, unknown>) => void;
  refreshInteraction: () => Promise<void>;
  resetMetrics: () => void;
  showConversation: (objective: string) => void;
  showError: (error: unknown) => void;
  appendEvent: (event: TaskEvent) => void;
  renderChangedFiles: (changedFiles: string[]) => void;
  renderVerificationState: (element: HTMLElement, passed: boolean | null) => void;
  renderResult: (payload: Record<string, unknown>) => void;
  renderUsage: (usage: UsageSummary | null) => Promise<void>;
  tokenPrices: (settings: Record<string, unknown>) => TokenPrices | null;
  loadResult: () => Promise<void>;
  sessionEntries: (payload: Record<string, unknown>, gatewayUrl: string) => TaskHistoryEntry[];
  refreshSessions: (append?: boolean) => Promise<void>;
  prepareRun: (objective: string, title?: string) => void;
  steer: (mode: "supplement" | "answer") => Promise<void>;
  runAgent: (text?: string | undefined, images?: ImageAttachment[]) => Promise<void>;
  restoreTask: (entry: TaskHistoryEntry) => Promise<void>;
  resetTask: () => void;
  setInspectorCollapsed: (collapsed: boolean) => void;
  browseWorkspace: () => Promise<void>;
  cyclePermission: () => void;
}

