"""Application ports. Adapters own SQL, filesystem and wire representations."""

from pathlib import Path
from typing import Any, Protocol

from bit_agent.tools.models import ToolResult


class StoragePort(Protocol):
    directory: Path

    async def call(self, operation: str, *args: Any) -> Any: ...
    def close(self) -> None: ...


class DiagnosticSnapshotPort(Protocol):
    async def diagnostic_snapshot(self, task_id: str | None = None) -> dict[str, Any]: ...


class ChangeJournalPort(Protocol):
    entries: list[dict]

    def prepare(self, call_id: str, patch: str) -> dict: ...
    def begin(self, entry: dict) -> None: ...
    def finish(self, entry: dict) -> None: ...
    def public(self) -> dict: ...
    def review(self, change_id: str, action: str) -> dict: ...


class JournalFactory(Protocol):
    def __call__(self, root: Path, directory: Path) -> ChangeJournalPort: ...


class ProjectVerifier(Protocol):
    async def __call__(self, root: Path, changed: list[str], call_id: str) -> ToolResult: ...


class AcceptanceWorkspacePort(Protocol):
    root: Path
    snapshot_id: str

    async def __aenter__(self) -> "AcceptanceWorkspacePort": ...
    async def __aexit__(self, *args: Any) -> None: ...
    async def write_test(self, project: str, filename: str, content: str) -> str: ...
    async def run_test(self, project: str, target: str, language: str, call_id: str) -> dict: ...
    async def unchanged(self) -> bool: ...
    async def save_report(self, report: dict) -> None: ...


class AcceptanceWorkspaceFactory(Protocol):
    def __call__(self, root: Path, artifacts: Path) -> AcceptanceWorkspacePort: ...
